# model configuration
#
model_path: logs/ep081-loss0.064-val_loss0.040.pth
is_prune: true
#model_path: "model_data/test.pth"
#is_prune: false
#
confidence: 0.5
nms_iou: 0.5

# train and predict
mode: "fps" # predict, dir_predict, video, fps
classes_path: "model_data/person.txt"

# prune 
backbone_normal: [1, 2, 8, 8, 4]
backbone_prune: [1, 2, 4, 4, 2]